### ISSUE TITLE
Did it support query the docs with selector?

### ISSUE THREAD

**Issue by lovelife100** [cloudant-labs/go-cloudant#8]
Hi I try to use this lib to connect to my cloudant database,
and I want to do query in cloudant, but I did not find in the code how to query with selector in the code.

Could you give me example if it support query docs with selector

**Comment by smithsz** [comment]
Unfortunately the feature isn't supported. I'm afraid this library isn't a priority for us at the moment so we won't be adding any new features in the short-term.

Any contributions to the library are most welcome. Just open a PR and we'll happily review your work.

Thanks.
